### ISSUE TITLE
Error in return statement

### ISSUE THREAD

**Issue by Ludhe009** [SanketW12/react-scanned-qr#1]
Hi, im trying to use your code for a qrscanner in a react and typescript project. But I get this error "import QrReader
JSX element type 'QrReader' does not have any construct or call signatures. " In the return statement for the QrReader component. Any idea how to fix that?

**Comment by SanketW12** [comment]
Hi @Ludhe009, Please use `react-qr-reader` if you only want a scanner for QR. This package is components only compatible with each other. You can read docs [here](https://www.npmjs.com/package/react-scanned-qr). To fix your problem you can install `react-qr-reader` with `npm install react-qr-reader` or `yarn add react-qr-reader` or try installing latest version.

**Comment by Ludhe009** [comment]
Yes thats the package im using, I couldn't install it because of react 18.2.0 but it seemed to have worked with npm install react-qr-reader --legacy-peer-deps

**Comment by SanketW12** [comment]
This error is specific to `npm`. You can use yarn or can use `--legacy-peer-deps` to ignore all peerDependencies when installing.

**Comment by Ludhe009** [comment]
Yes I used --legacy-peer-deps so I have react-qr-reader installed. This is the error I get in the code: JSX element type 'QrReader' does not have any construct or call signatures.ts(2604)
![9ed98c70fe44061b3a2290d34ad0745d](https://user-images.githubusercontent.com/99077619/193260013-f6b743a7-cf1f-4ee8-add4-d08294f31a41.png)

**Comment by SanketW12** [comment]
Can you mention the library and provide a proper error message? Because QrReader is not a component of `react-scanned-qr`.

**Comment by Ludhe009** [comment]
webpack compiled with 2 errors
ERROR in src/components/QRcodeScanner.tsx:83:10
TS2604: JSX element type 'QrReader' does not have any construct or call signatures.
    81 |         </button>
    82 |       ) : (
  > 83 |         <QrReader
       |          ^^^^^^^^
    84 |           onScan={handleScan}
    85 |           onError={onError}
    86 |           onLoad={onLoad}
Failed to compile.

Attempted import error: 'react-qr-reader' does not contain a default export (imported as 'QrReader').
ERROR in ./src/components/QRcodeScanner.tsx 74:36-44
export 'default' (imported as 'QrReader') was not found in 'react-qr-reader' (possible exports: QrReader, useQrReader)

i use import QrReader from 'react-qr-reader'
My QRcodeScanner.tsx is basicly a copy of your QRScanner.tsx right now, i just want it to work and then Im gonna change what it does onScanned

**Comment by SanketW12** [comment]
`raect-qr-reader` does not have a default export in your version. Please check with versions in `package.json`
> Attempted import error: 'react-qr-reader' does not contain a default export (imported as 'QrReader').

**Comment by Ludhe009** [comment]
This is my package.json
{
  "name": "c2-app",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@emotion/react": "^11.10.4",
    "@emotion/styled": "^11.10.4",
    "@mui/material": "^5.10.7",
    "@testing-library/jest-dom": "^5.16.5",
    "@testing-library/react": "^13.4.0",
    "@testing-library/user-event": "^13.5.0",
    "@types/jest": "^27.5.2",
    "@types/node": "^16.11.60",
    "@types/react": "^18.0.21",
    "@types/react-dom": "^18.0.6",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-qr-reader": "^3.0.0-beta-1",
    "react-router-dom": "^6.4.1",
    "react-scripts": "5.0.1",
    "socket.io-client": "^4.5.2",
    "typescript": "^4.8.3",
    "web-vitals": "^2.1.4"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}

**Comment by SanketW12** [comment]
Try using older versions. ex 2.2.1
>"react-qr-reader": "^3.0.0-beta-1",

**Comment by Ludhe009** [comment]
Okay it works now, thanks a lot for the help
